name: Release and Publish

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Needed to compare versions between commits

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Check if version has changed
        id: check-version
        run: |
          PREVIOUS_VERSION=$(git show HEAD^:package.json | jq -r .version)
          CURRENT_VERSION=$(jq -r .version package.json)
          if [ "$PREVIOUS_VERSION" != "$CURRENT_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: steps.check-version.outputs.version_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.check-version.outputs.new_version }}
          release_name: Release v${{ steps.check-version.outputs.new_version }}
          draft: false
          prerelease: false

      - name: Publish to npm
        if: steps.check-version.outputs.version_changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
